# _config.yml

title: romdown
description: A site for downloading ROM binary files.
baseurl: "/romdown"
url: "https://linuxx881.github.io/romdown"

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
